[theme]
primaryColor = "#10B981"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0F172A"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
